"use-client"
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <div className="bg-gray-100 min-h-screen min-w-screen p-6 sm:p-20">
                {children}
            </div>
        </html>
    );
}
